let v:errors = []

call assert_equal(1, 1, '1 = 1')
call assert_equal(1, 2, '1 = 2')

call test#end()
